algoritmo "semnome"
// Função :
// Autor :
// Data : 28/08/2021
// Seção de Declarações 
var

    ano, nasc , idade: Inteiro

inicio

      Escreva ("Em que ano estamos?")
      Leia (ano)
      Escreva ("Em que ano você nasceu?")
      Leia (nasc)
      idade <- ano - nasc
      Escreval ("Em", ano, "voce tera", idade, "anos")
      Se (idade >= 18) entao
      Escreval ("Você é maio que 18")
      
      Fimse


fimalgoritmo
